---
# tasks file for nginx-container

- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0664

- name: Intsall nginx.
  yum:
    name: "{{ nginx_package_name }}"
    state: installed
    enablerepo: nginx

- name: Create nginx user
  user:
    name: nginx
    uid: 1000
    group: root
    createhome: no

- name: Set permissions on /var/log/nginx
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Set permissions on /var/www
  file:
    path: /var/www
    state: directory 
    owner: nginx
    group: root
    mode: 0555

# Vhost configuration.
- include: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: nginx 
    group: root
    mode: 0664

