---
# tasks file for nginx-container

- name: Enable nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0664

- name: Intsall nginx
  yum:
    name: "{{ nginx_package_name }}"
    state: installed
    enablerepo: nginx

- name: Create nginx user
  user:
    name: nginx
    uid: 1000
    group: root
    createhome: no

- name: Set permissions on /var/log/nginx
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Set permissions on /var/cache/nginx/client_temp
  file:
    path: /var/cache/nginx/client_temp
    owner: nginx
    group: root
    mode: 0775 
    recurse: yes

- name: Remove log files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log 

- name: Link stdout and stderr to nginx log system
  file:
    path: "{{ item.path }}" 
    src: "{{ item.src }}" 
    state: link
  with_items:
    - path: /var/log/nginx/access.log
      src: /dev/stdout 
    - path: /var/log/nginx/error.log
      src: /dev/stderr

# Vhost configuration.
- include: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: nginx 
    group: root
    mode: 0664

